oot@TRC:/home/trc/Videos/docker# sudo apt install npm -y
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following additional packages will be installed:
  gyp libjs-events libjs-highlight.js libjs-inherits libjs-is-typedarray libjs-psl libjs-source-map libjs-sprintf-js
  libjs-typedarray-to-buffer libnode-dev libnode72 libssl-dev libuv1-dev node-abab node-abbrev node-agent-base node-ansi-regex
  node-ansi-styles node-ansistyles node-aproba node-archy node-are-we-there-yet node-argparse node-arrify node-asap node-asynckit
  node-balanced-match node-brace-expansion node-builtins node-cacache node-chalk node-chownr node-clean-yaml-object node-cli-table node-clone
  node-color-convert node-color-name node-colors node-columnify node-combined-stream node-commander node-console-control-strings
  node-copy-concurrently node-core-util-is node-coveralls node-cssom node-cssstyle node-debug node-decompress-response node-defaults
  node-delayed-stream node-delegates node-depd node-diff node-encoding node-end-of-stream node-err-code node-escape-string-regexp node-esprima
  node-events node-fancy-log node-fetch node-foreground-child node-form-data node-fs-write-stream-atomic node-fs.realpath node-function-bind
  node-gauge node-get-stream node-glob node-got node-graceful-fs node-growl node-gyp node-has-flag node-has-unicode node-hosted-git-info
  node-https-proxy-agent node-iconv-lite node-iferr node-imurmurhash node-indent-string node-inflight node-inherits node-ini node-ip
  node-ip-regex node-is-buffer node-is-plain-obj node-is-typedarray node-isarray node-isexe node-js-yaml node-jsdom node-json-buffer
  node-json-parse-better-errors node-jsonparse node-kind-of node-lcov-parse node-lodash-packages node-log-driver node-lowercase-keys
  node-lru-cache node-mime node-mime-types node-mimic-response node-minimatch node-minimist node-minipass node-mkdirp node-move-concurrently
  node-ms node-mute-stream node-negotiator node-nopt node-normalize-package-data node-npm-bundled node-npm-package-arg node-npmlog
  node-object-assign node-once node-opener node-osenv node-p-cancelable node-p-map node-path-is-absolute node-process-nextick-args
  node-promise-inflight node-promise-retry node-promzard node-psl node-pump node-punycode node-quick-lru node-read node-read-package-json
  node-readable-stream node-resolve node-retry node-rimraf node-run-queue node-safe-buffer node-semver node-set-blocking node-signal-exit
  node-slash node-slice-ansi node-source-map node-source-map-support node-spdx-correct node-spdx-exceptions node-spdx-expression-parse
  node-spdx-license-ids node-sprintf-js node-ssri node-stack-utils node-stealthy-require node-string-decoder node-string-width node-strip-ansi
  node-supports-color node-tap node-tap-mocha-reporter node-tap-parser node-tar node-text-table node-time-stamp node-tmatch node-tough-cookie
  node-typedarray-to-buffer node-unique-filename node-universalify node-util-deprecate node-validate-npm-package-license
  node-validate-npm-package-name node-wcwidth.js node-webidl-conversions node-whatwg-fetch node-which node-wide-align node-wrappy
  node-write-file-atomic node-ws node-yallist nodejs nodejs-doc
Suggested packages:
  libjs-angularjs libssl-doc node-nyc
The following NEW packages will be installed:
  gyp libjs-events libjs-highlight.js libjs-inherits libjs-is-typedarray libjs-psl libjs-source-map libjs-sprintf-js
  libjs-typedarray-to-buffer libnode-dev libnode72 libssl-dev libuv1-dev node-abab node-abbrev node-agent-base node-ansi-regex
  node-ansi-styles node-ansistyles node-aproba node-archy node-are-we-there-yet node-argparse node-arrify node-asap node-asynckit
  node-balanced-match node-brace-expansion node-builtins node-cacache node-chalk node-chownr node-clean-yaml-object node-cli-table node-clone
  node-color-convert node-color-name node-colors node-columnify node-combined-stream node-commander node-console-control-strings
  node-copy-concurrently node-core-util-is node-coveralls node-cssom node-cssstyle node-debug node-decompress-response node-defaults
  node-delayed-stream node-delegates node-depd node-diff node-encoding node-end-of-stream node-err-code node-escape-string-regexp node-esprima
  node-events node-fancy-log node-fetch node-foreground-child node-form-data node-fs-write-stream-atomic node-fs.realpath node-function-bind
  node-gauge node-get-stream node-glob node-got node-graceful-fs node-growl node-gyp node-has-flag node-has-unicode node-hosted-git-info
  node-https-proxy-agent node-iconv-lite node-iferr node-imurmurhash node-indent-string node-inflight node-inherits node-ini node-ip
  node-ip-regex node-is-buffer node-is-plain-obj node-is-typedarray node-isarray node-isexe node-js-yaml node-jsdom node-json-buffer
  node-json-parse-better-errors node-jsonparse node-kind-of node-lcov-parse node-lodash-packages node-log-driver node-lowercase-keys
  node-lru-cache node-mime node-mime-types node-mimic-response node-minimatch node-minimist node-minipass node-mkdirp node-move-concurrently
  node-ms node-mute-stream node-negotiator node-nopt node-normalize-package-data node-npm-bundled node-npm-package-arg node-npmlog
  node-object-assign node-once node-opener node-osenv node-p-cancelable node-p-map node-path-is-absolute node-process-nextick-args
  node-promise-inflight node-promise-retry node-promzard node-psl node-pump node-punycode node-quick-lru node-read node-read-package-json
  node-readable-stream node-resolve node-retry node-rimraf node-run-queue node-safe-buffer node-semver node-set-blocking node-signal-exit
  node-slash node-slice-ansi node-source-map node-source-map-support node-spdx-correct node-spdx-exceptions node-spdx-expression-parse
  node-spdx-license-ids node-sprintf-js node-ssri node-stack-utils node-stealthy-require node-string-decoder node-string-width node-strip-ansi
  node-supports-color node-tap node-tap-mocha-reporter node-tap-parser node-tar node-text-table node-time-stamp node-tmatch node-tough-cookie
  node-typedarray-to-buffer node-unique-filename node-universalify node-util-deprecate node-validate-npm-package-license
  node-validate-npm-package-name node-wcwidth.js node-webidl-conversions node-whatwg-fetch node-which node-wide-align node-wrappy
  node-write-file-atomic node-ws node-yallist nodejs nodejs-doc npm
0 upgraded, 187 newly installed, 0 to remove and 52 not upgraded.
Need to get 21.1 MB of archives.
After this operation, 103 MB of additional disk space will be used.
Get:1 http://archive.ubuntu.com/ubuntu jammy/universe amd64 gyp all 0.1+20210831gitd6c5dd5-5 [238 kB]
Get:2 http://archive.ubuntu.com/ubuntu jammy/universe amd64 libjs-events all 3.3.0+~3.0.0-2 [9,734 B]
Get:3 http://archive.ubuntu.com/ubuntu jammy/universe amd64 libjs-highlight.js all 9.18.5+dfsg1-1 [367 kB]
Get:4 http://archive.ubuntu.com/ubuntu jammy/universe amd64 libjs-is-typedarray all 1.0.0-4 [3,804 B]
Get:5 http://archive.ubuntu.com/ubuntu jammy/universe amd64 libjs-psl all 1.8.0+ds-6 [76.3 kB]
Get:6 http://archive.ubuntu.com/ubuntu jammy/universe amd64 libjs-sprintf-js all 1.1.2+ds1+~1.1.2-1 [12.8 kB]
Get:7 http://archive.ubuntu.com/ubuntu jammy/universe amd64 libjs-typedarray-to-buffer all 4.0.0-2 [4,658 B]
Get:8 http://archive.ubuntu.com/ubuntu jammy-security/main amd64 libssl-dev amd64 3.0.2-0ubuntu1.19 [2,376 kB]
Get:9 http://archive.ubuntu.com/ubuntu jammy-security/main amd64 libuv1-dev amd64 1.43.0-1ubuntu0.1 [130 kB]
Get:10 http://archive.ubuntu.com/ubuntu jammy-security/universe amd64 libnode72 amd64 12.22.9~dfsg-1ubuntu3.6 [10.8 MB]
Get:11 http://archive.ubuntu.com/ubuntu jammy-security/universe amd64 libnode-dev amd64 12.22.9~dfsg-1ubuntu3.6 [609 kB]
Get:12 http://archive.ubuntu.com/ubuntu jammy-security/universe amd64 nodejs amd64 12.22.9~dfsg-1ubuntu3.6 [122 kB]
Get:13 http://archive.ubuntu.com/ubuntu jammy/universe amd64 node-abab all 2.0.5-2 [6,578 B]
Get:14 http://archive.ubuntu.com/ubuntu jammy/universe amd64 node-ms all 2.1.3+~cs0.7.31-2 [5,782 B]
Get:15 http://archive.ubuntu.com/ubuntu jammy/universe amd64 node-debug all 4.3.2+~cs4.1.7-1 [17.6 kB]
Get:16 http://archive.ubuntu.com/ubuntu jammy/universe amd64 node-yallist all 4.0.0+~4.0.1-1 [8,322 B]
Get:17 http://archive.ubuntu.com/ubuntu jammy/universe amd64 node-lru-cache all 6.0.0+~5.1.1-1 [11.3 kB]
Get:18 http://archive.ubuntu.com/ubuntu jammy/universe amd64 node-semver all 7.3.5+~7.3.8-1 [41.5 kB]
Get:19 http://archive.ubuntu.com/ubuntu jammy/universe amd64 node-agent-base all 6.0.2+~cs5.4.2-1 [17.9 kB]
Get:20 http://archive.ubuntu.com/ubuntu jammy/universe amd64 node-ansi-regex all 5.0.1-1 [4,984 B]
Get:21 http://archive.ubuntu.com/ubuntu jammy/universe amd64 node-ansistyles all 0.1.3-5 [4,546 B]
Get:22 http://archive.ubuntu.com/ubuntu jammy/universe amd64 node-aproba all 2.0.0-2 [5,620 B]
Get:23 http://archive.ubuntu.com/ubuntu jammy/universe amd64 node-delegates all 1.0.0-3 [4,280 B]                                              
Get:24 http://archive.ubuntu.com/ubuntu jammy/universe amd64 libjs-inherits all 2.0.4-4 [3,468 B]                                              
Get:25 http://archive.ubuntu.com/ubuntu jammy/universe amd64 node-inherits all 2.0.4-4 [3,010 B]                                               
Get:26 http://archive.ubuntu.com/ubuntu jammy/universe amd64 node-core-util-is all 1.0.3-1 [4,066 B]                                           
Get:27 http://archive.ubuntu.com/ubuntu jammy/universe amd64 node-safe-buffer all 5.2.1+~cs2.1.2-2 [15.7 kB]                                   
Get:28 http://archive.ubuntu.com/ubuntu jammy/universe amd64 node-string-decoder all 1.3.0-5 [7,046 B]                                         
Get:29 http://archive.ubuntu.com/ubuntu jammy/universe amd64 node-process-nextick-args all 2.0.1-2 [3,730 B]                                   
Get:30 http://archive.ubuntu.com/ubuntu jammy/universe amd64 node-util-deprecate all 1.0.2-3 [4,202 B]                                         
Get:31 http://archive.ubuntu.com/ubuntu jammy/universe amd64 node-isarray all 2.0.5-3 [3,934 B]                                                
Get:32 http://archive.ubuntu.com/ubuntu jammy/universe amd64 node-readable-stream all 3.6.0+~cs3.0.0-1 [32.6 kB]                               
Get:33 http://archive.ubuntu.com/ubuntu jammy/universe amd64 node-are-we-there-yet all 3.0.0+~1.1.0-1 [8,920 B]                                
Get:34 http://archive.ubuntu.com/ubuntu jammy/universe amd64 node-arrify all 2.0.1-2 [3,610 B]                                                 
Get:35 http://archive.ubuntu.com/ubuntu jammy/universe amd64 node-asap all 2.0.6+~2.0.0-1 [14.4 kB]                                            
Get:36 http://archive.ubuntu.com/ubuntu jammy/universe amd64 node-asynckit all 0.4.0-4 [10.6 kB]                                               
Get:37 http://archive.ubuntu.com/ubuntu jammy/universe amd64 node-builtins all 4.0.0-1 [3,860 B]                                               
Get:38 http://archive.ubuntu.com/ubuntu jammy/universe amd64 node-chownr all 2.0.0-1 [4,404 B]                                                 
Get:39 http://archive.ubuntu.com/ubuntu jammy/universe amd64 node-fs.realpath all 1.0.0-2 [6,106 B]                                            
Get:40 http://archive.ubuntu.com/ubuntu jammy/universe amd64 node-wrappy all 1.0.2-2 [3,658 B]                                                 
Get:41 http://archive.ubuntu.com/ubuntu jammy/universe amd64 node-once all 1.4.0-4 [4,708 B]                                                   
Get:42 http://archive.ubuntu.com/ubuntu jammy/universe amd64 node-inflight all 1.0.6-2 [3,940 B]                                               
Get:43 http://archive.ubuntu.com/ubuntu jammy/universe amd64 node-balanced-match all 2.0.0-1 [4,910 B]                                         
Get:44 http://archive.ubuntu.com/ubuntu jammy/universe amd64 node-brace-expansion all 2.0.1-1 [7,458 B]                                        
Get:45 http://archive.ubuntu.com/ubuntu jammy/universe amd64 node-minimatch all 3.1.1+~3.0.5-1 [16.9 kB]                                       
Get:46 http://archive.ubuntu.com/ubuntu jammy/universe amd64 node-path-is-absolute all 2.0.0-2 [4,062 B]                                       
Get:47 http://archive.ubuntu.com/ubuntu jammy/universe amd64 node-glob all 7.2.1+~cs7.6.15-1 [131 kB]                                          
Get:48 http://archive.ubuntu.com/ubuntu jammy/universe amd64 node-graceful-fs all 4.2.4+repack-1 [12.5 kB]                                     
Get:49 http://archive.ubuntu.com/ubuntu jammy/universe amd64 node-mkdirp all 1.0.4+~1.0.2-1 [11.4 kB]                                          
Get:50 http://archive.ubuntu.com/ubuntu jammy/universe amd64 node-iferr all 1.0.2+~1.0.2-1 [4,610 B]                                           
Get:51 http://archive.ubuntu.com/ubuntu jammy/universe amd64 node-imurmurhash all 0.1.4+dfsg+~0.1.1-1 [8,510 B]                                
Get:52 http://archive.ubuntu.com/ubuntu jammy/universe amd64 node-fs-write-stream-atomic all 1.0.10-5 [5,256 B]                                
Get:53 http://archive.ubuntu.com/ubuntu jammy/universe amd64 node-rimraf all 3.0.2-1 [10.1 kB]                                                 
Get:54 http://archive.ubuntu.com/ubuntu jammy/universe amd64 node-run-queue all 2.0.0-2 [5,092 B]                                              
Get:55 http://archive.ubuntu.com/ubuntu jammy/universe amd64 node-copy-concurrently all 1.0.5-8 [7,118 B]                                      
Get:56 http://archive.ubuntu.com/ubuntu jammy/universe amd64 node-move-concurrently all 1.0.1-4 [5,120 B]                                      
Get:57 http://archive.ubuntu.com/ubuntu jammy/universe amd64 node-escape-string-regexp all 4.0.0-2 [4,328 B]                                   
Get:58 http://archive.ubuntu.com/ubuntu jammy/universe amd64 node-indent-string all 4.0.0-2 [4,122 B]                                          
Get:59 http://archive.ubuntu.com/ubuntu jammy/universe amd64 node-p-map all 4.0.0+~3.1.0+~3.0.1-1 [8,058 B]                                    
Get:60 http://archive.ubuntu.com/ubuntu jammy/universe amd64 node-promise-inflight all 1.0.1+~1.0.0-1 [4,896 B]                                
Get:61 http://archive.ubuntu.com/ubuntu jammy/universe amd64 node-ssri all 8.0.1-2 [19.6 kB]                                                   
Get:62 http://archive.ubuntu.com/ubuntu jammy/universe amd64 node-unique-filename all 1.1.1+ds-1 [3,832 B]                                     
Get:63 http://archive.ubuntu.com/ubuntu jammy/universe amd64 node-cacache all 15.0.5+~cs13.9.21-3 [34.9 kB]                                    
Get:64 http://archive.ubuntu.com/ubuntu jammy/universe amd64 node-clean-yaml-object all 0.1.0-5 [4,718 B]                                      
Get:65 http://archive.ubuntu.com/ubuntu jammy/universe amd64 node-clone all 2.1.2-3 [8,344 B]                                                  
Get:66 http://archive.ubuntu.com/ubuntu jammy/universe amd64 node-color-name all 1.1.4+~1.1.1-2 [6,076 B]                                      
Get:67 http://archive.ubuntu.com/ubuntu jammy/universe amd64 node-color-convert all 2.0.1-1 [10.2 kB]                                          
Get:68 http://archive.ubuntu.com/ubuntu jammy/universe amd64 node-colors all 1.4.0-3 [12.3 kB]                                                 
Get:69 http://archive.ubuntu.com/ubuntu jammy/universe amd64 node-strip-ansi all 6.0.1-1 [4,184 B]                                             
Get:70 http://archive.ubuntu.com/ubuntu jammy/universe amd64 node-defaults all 1.0.3+~1.0.3-1 [4,288 B]                                        
Get:71 http://archive.ubuntu.com/ubuntu jammy/universe amd64 node-wcwidth.js all 1.0.2-1 [7,278 B]                                             
Get:72 http://archive.ubuntu.com/ubuntu jammy/universe amd64 node-columnify all 1.5.4+~1.5.1-1 [12.6 kB]                                       
Get:73 http://archive.ubuntu.com/ubuntu jammy/universe amd64 node-console-control-strings all 1.1.0-2 [5,428 B]                                
Get:74 http://archive.ubuntu.com/ubuntu jammy/universe amd64 node-growl all 1.10.5-4 [7,064 B]                                                 
Get:75 http://archive.ubuntu.com/ubuntu jammy/universe amd64 node-sprintf-js all 1.1.2+ds1+~1.1.2-1 [3,916 B]                                  
Get:76 http://archive.ubuntu.com/ubuntu jammy/universe amd64 node-argparse all 2.0.1-2 [33.2 kB]                                               
Get:77 http://archive.ubuntu.com/ubuntu jammy/universe amd64 node-esprima all 4.0.1+ds+~4.0.3-2 [69.3 kB]                                      
Get:78 http://archive.ubuntu.com/ubuntu jammy/universe amd64 node-js-yaml all 4.1.0+dfsg+~4.0.5-6 [62.7 kB]                                    
Get:79 http://archive.ubuntu.com/ubuntu jammy/universe amd64 node-lcov-parse all 1.0.0+20170612git80d039574ed9-5 [5,084 B]                     
Get:80 http://archive.ubuntu.com/ubuntu jammy/universe amd64 node-log-driver all 1.2.7+git+20180219+bba1761737-7 [5,436 B]                     
Get:81 http://archive.ubuntu.com/ubuntu jammy/universe amd64 node-is-plain-obj all 3.0.0-2 [3,994 B]                                           
Get:82 http://archive.ubuntu.com/ubuntu jammy/universe amd64 node-is-buffer all 2.0.5-2 [4,128 B]                                              
Get:83 http://archive.ubuntu.com/ubuntu jammy/universe amd64 node-kind-of all 6.0.3+dfsg-2 [8,628 B]                                           
Get:84 http://archive.ubuntu.com/ubuntu jammy/universe amd64 node-minimist all 1.2.5+~cs5.3.2-1 [9,434 B]                                      
Get:85 http://archive.ubuntu.com/ubuntu jammy/universe amd64 node-cssom all 0.4.4-3 [14.1 kB]                                                  
Get:86 http://archive.ubuntu.com/ubuntu jammy/universe amd64 node-cssstyle all 2.3.0-2 [30.3 kB]                                               
Get:87 http://archive.ubuntu.com/ubuntu jammy/universe amd64 node-delayed-stream all 1.0.0-5 [5,464 B]                                         
Get:88 http://archive.ubuntu.com/ubuntu jammy/universe amd64 node-combined-stream all 1.0.8+~1.0.3-1 [7,432 B]                                 
Get:89 http://archive.ubuntu.com/ubuntu jammy/universe amd64 node-mime all 3.0.0+dfsg+~cs3.96.1-1 [38.1 kB]                                    
Get:90 http://archive.ubuntu.com/ubuntu jammy/universe amd64 node-mime-types all 2.1.33-1 [6,944 B]                                            
Get:91 http://archive.ubuntu.com/ubuntu jammy/universe amd64 node-form-data all 3.0.1-1 [13.4 kB]                                              
Get:92 http://archive.ubuntu.com/ubuntu jammy/universe amd64 node-events all 3.3.0+~3.0.0-2 [3,090 B]                                          
Get:93 http://archive.ubuntu.com/ubuntu jammy/universe amd64 node-https-proxy-agent all 5.0.0+~cs8.0.0-3 [16.4 kB]                             
Get:94 http://archive.ubuntu.com/ubuntu jammy/universe amd64 node-iconv-lite all 0.6.3-2 [167 kB]                                              
Get:95 http://archive.ubuntu.com/ubuntu jammy/universe amd64 node-lodash-packages all 4.17.21+dfsg+~cs8.31.198.20210220-5 [166 kB]             
Get:96 http://archive.ubuntu.com/ubuntu jammy/universe amd64 node-stealthy-require all 1.1.1-5 [7,176 B]                                       
Get:97 http://archive.ubuntu.com/ubuntu jammy/universe amd64 node-punycode all 2.1.1-5 [9,902 B]                                               
Get:98 http://archive.ubuntu.com/ubuntu jammy/universe amd64 node-psl all 1.8.0+ds-6 [39.6 kB]                                                 
Get:99 http://archive.ubuntu.com/ubuntu jammy/universe amd64 node-universalify all 2.0.0-3 [4,266 B]                                           
Get:100 http://archive.ubuntu.com/ubuntu jammy/universe amd64 node-tough-cookie all 4.0.0-2 [31.7 kB]                                          
Get:101 http://archive.ubuntu.com/ubuntu jammy/universe amd64 node-webidl-conversions all 7.0.0~1.1.0+~cs15.1.20180823-2 [27.5 kB]             
Get:102 http://archive.ubuntu.com/ubuntu jammy/universe amd64 node-commander all 9.0.0-2 [48.0 kB]                                             
Get:103 http://archive.ubuntu.com/ubuntu jammy/universe amd64 node-mute-stream all 0.0.8+~0.0.1-1 [6,448 B]                                    
Get:104 http://archive.ubuntu.com/ubuntu jammy/universe amd64 node-read all 1.0.7-3 [5,478 B]                                                  
Get:105 http://archive.ubuntu.com/ubuntu jammy/universe amd64 node-ws all 8.5.0+~cs13.3.3-2 [49.5 kB]                                          
Get:106 http://archive.ubuntu.com/ubuntu jammy/universe amd64 node-jsdom all 19.0.0+~cs90.11.27-1 [446 kB]                                     
Get:107 http://archive.ubuntu.com/ubuntu jammy/universe amd64 node-fetch all 2.6.7+~2.5.12-1 [27.1 kB]                                         
Get:108 http://archive.ubuntu.com/ubuntu jammy/universe amd64 node-coveralls all 3.1.1-1 [14.2 kB]                                             
Get:109 http://archive.ubuntu.com/ubuntu jammy/universe amd64 node-mimic-response all 3.1.0-7 [5,430 B]                                        
Get:110 http://archive.ubuntu.com/ubuntu jammy/universe amd64 node-decompress-response all 6.0.0-2 [4,656 B]                                   
Get:111 http://archive.ubuntu.com/ubuntu jammy/universe amd64 node-diff all 5.0.0~dfsg+~5.0.1-3 [77.4 kB]                                      
Get:112 http://archive.ubuntu.com/ubuntu jammy/universe amd64 node-err-code all 2.0.3+dfsg-3 [4,918 B]                                         
Get:113 http://archive.ubuntu.com/ubuntu jammy/universe amd64 node-time-stamp all 2.2.0-1 [5,984 B]                                            
Get:114 http://archive.ubuntu.com/ubuntu jammy/universe amd64 node-fancy-log all 1.3.3+~cs1.3.1-2 [8,102 B]                                    
Get:115 http://archive.ubuntu.com/ubuntu jammy/universe amd64 node-signal-exit all 3.0.6+~3.0.1-1 [7,000 B]                                    
Get:116 http://archive.ubuntu.com/ubuntu jammy/universe amd64 node-foreground-child all 2.0.0-3 [5,542 B]                                      
Get:117 http://archive.ubuntu.com/ubuntu jammy/universe amd64 node-function-bind all 1.1.1+repacked+~1.0.3-1 [5,244 B]                         
Get:118 http://archive.ubuntu.com/ubuntu jammy/universe amd64 node-has-unicode all 2.0.1-4 [3,948 B]                                           
Get:119 http://archive.ubuntu.com/ubuntu jammy/universe amd64 node-ansi-styles all 4.3.0+~4.2.0-1 [8,968 B]                                    
Get:120 http://archive.ubuntu.com/ubuntu jammy/universe amd64 node-slice-ansi all 5.0.0+~cs9.0.0-4 [8,044 B]                                   
Get:121 http://archive.ubuntu.com/ubuntu jammy/universe amd64 node-string-width all 4.2.3+~cs13.2.3-1 [11.4 kB]                                
Get:122 http://archive.ubuntu.com/ubuntu jammy/universe amd64 node-wide-align all 1.1.3-4 [4,228 B]                                            
Get:123 http://archive.ubuntu.com/ubuntu jammy/universe amd64 node-gauge all 4.0.2-1 [16.3 kB]                                                 
Get:124 http://archive.ubuntu.com/ubuntu jammy/universe amd64 node-end-of-stream all 1.4.4+~1.4.1-1 [5,340 B]                                  
Get:125 http://archive.ubuntu.com/ubuntu jammy/universe amd64 node-pump all 3.0.0-5 [5,160 B]                                                  
Get:126 http://archive.ubuntu.com/ubuntu jammy/universe amd64 node-get-stream all 6.0.1-1 [7,324 B]                                            
Get:127 http://archive.ubuntu.com/ubuntu jammy/universe amd64 node-lowercase-keys all 2.0.0-2 [3,754 B]                                        
Get:128 http://archive.ubuntu.com/ubuntu jammy/universe amd64 node-json-buffer all 3.0.1-1 [3,812 B]                                           
Get:129 http://archive.ubuntu.com/ubuntu jammy/universe amd64 node-p-cancelable all 2.1.1-1 [7,358 B]                                          
Get:130 http://archive.ubuntu.com/ubuntu jammy/universe amd64 node-quick-lru all 5.1.1-1 [5,532 B]                                             
Get:131 http://archive.ubuntu.com/ubuntu jammy/universe amd64 node-got all 11.8.3+~cs58.7.37-1 [122 kB]                                        
Get:132 http://archive.ubuntu.com/ubuntu jammy/universe amd64 node-has-flag all 4.0.0-2 [4,228 B]                                              
Get:133 http://archive.ubuntu.com/ubuntu jammy/universe amd64 node-hosted-git-info all 4.0.2-1 [9,006 B]                                       
Get:134 http://archive.ubuntu.com/ubuntu jammy/universe amd64 node-ip all 1.1.5+~1.1.0-1 [8,140 B]                                             
Get:135 http://archive.ubuntu.com/ubuntu jammy/universe amd64 node-ip-regex all 4.3.0+~4.1.1-1 [5,254 B]                                       
Get:136 http://archive.ubuntu.com/ubuntu jammy/universe amd64 node-is-typedarray all 1.0.0-4 [2,072 B]                                         
Get:137 http://archive.ubuntu.com/ubuntu jammy/universe amd64 node-isexe all 2.0.0+~2.0.1-4 [6,102 B]                                          
Get:138 http://archive.ubuntu.com/ubuntu jammy/universe amd64 node-json-parse-better-errors all 1.0.2+~cs3.3.1-1 [7,328 B]                     
Get:139 http://archive.ubuntu.com/ubuntu jammy/universe amd64 node-encoding all 0.1.13-2 [4,366 B]                                             
Get:140 http://archive.ubuntu.com/ubuntu jammy/universe amd64 node-jsonparse all 1.3.1-10 [8,060 B]                                            
Get:141 http://archive.ubuntu.com/ubuntu jammy/universe amd64 node-minipass all 3.1.6+~cs8.7.18-1 [32.9 kB]                                    
Get:142 http://archive.ubuntu.com/ubuntu jammy/universe amd64 node-npm-bundled all 1.1.2-1 [6,228 B]                                           
Get:143 http://archive.ubuntu.com/ubuntu jammy/universe amd64 node-osenv all 0.1.5+~0.1.0-1 [5,896 B]                                          
Get:144 http://archive.ubuntu.com/ubuntu jammy/universe amd64 node-validate-npm-package-name all 3.0.0-4 [5,058 B]                             
Get:145 http://archive.ubuntu.com/ubuntu jammy/universe amd64 node-npm-package-arg all 8.1.5-1 [8,132 B]                                       
Get:146 http://archive.ubuntu.com/ubuntu jammy/universe amd64 node-object-assign all 4.1.1-6 [4,754 B]                                         
Get:147 http://archive.ubuntu.com/ubuntu jammy/universe amd64 node-opener all 1.5.2+~1.4.0-1 [6,000 B]                                         
Get:148 http://archive.ubuntu.com/ubuntu jammy/universe amd64 node-retry all 0.13.1+~0.12.1-1 [11.5 kB]                                        
Get:149 http://archive.ubuntu.com/ubuntu jammy/universe amd64 node-promise-retry all 2.0.1-2 [5,010 B]                                         
Get:150 http://archive.ubuntu.com/ubuntu jammy/universe amd64 node-promzard all 0.3.0-2 [6,888 B]                                              
Get:151 http://archive.ubuntu.com/ubuntu jammy/universe amd64 node-set-blocking all 2.0.0-2 [3,766 B]                                          
Get:152 http://archive.ubuntu.com/ubuntu jammy/universe amd64 node-slash all 3.0.0-2 [3,922 B]                                                 
Get:153 http://archive.ubuntu.com/ubuntu jammy/universe amd64 libjs-source-map all 0.7.0++dfsg2+really.0.6.1-9 [93.9 kB]                       
Get:154 http://archive.ubuntu.com/ubuntu jammy/universe amd64 node-source-map all 0.7.0++dfsg2+really.0.6.1-9 [33.6 kB]                        
Get:155 http://archive.ubuntu.com/ubuntu jammy/universe amd64 node-source-map-support all 0.5.21+ds+~0.5.4-1 [14.2 kB]                         
Get:156 http://archive.ubuntu.com/ubuntu jammy/universe amd64 node-spdx-license-ids all 3.0.11-1 [7,306 B]                                     
Get:157 http://archive.ubuntu.com/ubuntu jammy/universe amd64 node-spdx-exceptions all 2.3.0-2 [3,978 B]                                       
Get:158 http://archive.ubuntu.com/ubuntu jammy/universe amd64 node-spdx-expression-parse all 3.0.1+~3.0.1-1 [7,658 B]                          
Get:159 http://archive.ubuntu.com/ubuntu jammy/universe amd64 node-spdx-correct all 3.1.1-2 [5,476 B]                                          
Get:160 http://archive.ubuntu.com/ubuntu jammy/universe amd64 node-stack-utils all 2.0.5+~2.0.1-1 [9,368 B]                                    
Get:161 http://archive.ubuntu.com/ubuntu jammy/universe amd64 node-supports-color all 8.1.1+~8.1.1-1 [7,048 B]                                 
Get:162 http://archive.ubuntu.com/ubuntu jammy/universe amd64 node-tap-parser all 7.0.0+ds1-6 [19.4 kB]                                        
Get:163 http://archive.ubuntu.com/ubuntu jammy/universe amd64 node-tap-mocha-reporter all 3.0.7+ds-2 [39.2 kB]                                 
Get:164 http://archive.ubuntu.com/ubuntu jammy/universe amd64 node-text-table all 0.2.0-4 [4,762 B]                                            
Get:165 http://archive.ubuntu.com/ubuntu jammy/universe amd64 node-tmatch all 5.0.0-4 [6,002 B]                                                
Get:166 http://archive.ubuntu.com/ubuntu jammy/universe amd64 node-typedarray-to-buffer all 4.0.0-2 [2,242 B]                                  
Get:167 http://archive.ubuntu.com/ubuntu jammy/universe amd64 node-validate-npm-package-license all 3.0.4-2 [4,252 B]                          
Get:168 http://archive.ubuntu.com/ubuntu jammy/universe amd64 node-whatwg-fetch all 3.6.2-5 [15.0 kB]                                          
Get:169 http://archive.ubuntu.com/ubuntu jammy/universe amd64 node-write-file-atomic all 3.0.3+~3.0.2-1 [7,690 B]                              
Get:170 http://archive.ubuntu.com/ubuntu jammy-security/universe amd64 nodejs-doc all 12.22.9~dfsg-1ubuntu3.6 [2,411 kB]                       
Get:171 http://archive.ubuntu.com/ubuntu jammy/universe amd64 node-abbrev all 1.1.1+~1.1.2-1 [5,784 B]                                         
Get:172 http://archive.ubuntu.com/ubuntu jammy/universe amd64 node-archy all 1.0.0-4 [4,728 B]                                                 
Get:173 http://archive.ubuntu.com/ubuntu jammy/universe amd64 node-chalk all 4.1.2-1 [15.9 kB]                                                 
Get:174 http://archive.ubuntu.com/ubuntu jammy/universe amd64 node-cli-table all 0.3.11+~cs0.13.3-1 [23.2 kB]                                  
Get:175 http://archive.ubuntu.com/ubuntu jammy/universe amd64 node-depd all 2.0.0-2 [10.5 kB]                                                  
Get:176 http://archive.ubuntu.com/ubuntu jammy/universe amd64 node-nopt all 5.0.0-2 [11.3 kB]                                                  
Get:177 http://archive.ubuntu.com/ubuntu jammy/universe amd64 node-npmlog all 6.0.1+~4.1.4-1 [9,968 B]                                         
Get:178 http://archive.ubuntu.com/ubuntu jammy/universe amd64 node-tar all 6.1.11+ds1+~cs6.0.6-1 [38.8 kB]                                     
Get:179 http://archive.ubuntu.com/ubuntu jammy/universe amd64 node-which all 2.0.2+~cs1.3.2-2 [7,374 B]                                        
Get:180 http://archive.ubuntu.com/ubuntu jammy/universe amd64 node-gyp all 8.4.1-1 [34.7 kB]                                                   
Get:181 http://archive.ubuntu.com/ubuntu jammy/universe amd64 node-ini all 2.0.1-1 [6,528 B]                                                   
Get:182 http://archive.ubuntu.com/ubuntu jammy/universe amd64 node-negotiator all 0.6.2+~0.6.1-1 [10.3 kB]                                     
Get:183 http://archive.ubuntu.com/ubuntu jammy/universe amd64 node-resolve all 1.20.0+~cs5.27.9-1 [20.7 kB]                                    
Get:184 http://archive.ubuntu.com/ubuntu jammy/universe amd64 node-normalize-package-data all 3.0.3+~2.4.1-1 [12.8 kB]                         
Get:185 http://archive.ubuntu.com/ubuntu jammy/universe amd64 node-read-package-json all 4.1.1-1 [10.4 kB]                                     
Get:186 http://archive.ubuntu.com/ubuntu jammy/universe amd64 node-tap all 12.0.1+ds-4 [43.6 kB]                                               
Get:187 http://archive.ubuntu.com/ubuntu jammy/universe amd64 npm all 8.5.1~ds-1 [894 kB]                                                      
Fetched 21.1 MB in 16s (1,338 kB/s)                                                                                                            
Extracting templates from packages: 100%
Selecting previously unselected package gyp.
(Reading database ... 275667 files and directories currently installed.)
Preparing to unpack .../000-gyp_0.1+20210831gitd6c5dd5-5_all.deb ...
Unpacking gyp (0.1+20210831gitd6c5dd5-5) ...
Selecting previously unselected package libjs-events.
Preparing to unpack .../001-libjs-events_3.3.0+~3.0.0-2_all.deb ...
Unpacking libjs-events (3.3.0+~3.0.0-2) ...
Selecting previously unselected package libjs-highlight.js.
Preparing to unpack .../002-libjs-highlight.js_9.18.5+dfsg1-1_all.deb ...
Unpacking libjs-highlight.js (9.18.5+dfsg1-1) ...
Selecting previously unselected package libjs-is-typedarray.
Preparing to unpack .../003-libjs-is-typedarray_1.0.0-4_all.deb ...
Unpacking libjs-is-typedarray (1.0.0-4) ...
Selecting previously unselected package libjs-psl.
Preparing to unpack .../004-libjs-psl_1.8.0+ds-6_all.deb ...
Unpacking libjs-psl (1.8.0+ds-6) ...
Selecting previously unselected package libjs-sprintf-js.
Preparing to unpack .../005-libjs-sprintf-js_1.1.2+ds1+~1.1.2-1_all.deb ...
Unpacking libjs-sprintf-js (1.1.2+ds1+~1.1.2-1) ...
Selecting previously unselected package libjs-typedarray-to-buffer.
Preparing to unpack .../006-libjs-typedarray-to-buffer_4.0.0-2_all.deb ...
Unpacking libjs-typedarray-to-buffer (4.0.0-2) ...
Selecting previously unselected package libssl-dev:amd64.
Preparing to unpack .../007-libssl-dev_3.0.2-0ubuntu1.19_amd64.deb ...
Unpacking libssl-dev:amd64 (3.0.2-0ubuntu1.19) ...
Selecting previously unselected package libuv1-dev:amd64.
Preparing to unpack .../008-libuv1-dev_1.43.0-1ubuntu0.1_amd64.deb ...
Unpacking libuv1-dev:amd64 (1.43.0-1ubuntu0.1) ...
Selecting previously unselected package libnode72:amd64.
Preparing to unpack .../009-libnode72_12.22.9~dfsg-1ubuntu3.6_amd64.deb ...
Unpacking libnode72:amd64 (12.22.9~dfsg-1ubuntu3.6) ...
Selecting previously unselected package libnode-dev.
Preparing to unpack .../010-libnode-dev_12.22.9~dfsg-1ubuntu3.6_amd64.deb ...
Unpacking libnode-dev (12.22.9~dfsg-1ubuntu3.6) ...
Selecting previously unselected package nodejs.
Preparing to unpack .../011-nodejs_12.22.9~dfsg-1ubuntu3.6_amd64.deb ...
Unpacking nodejs (12.22.9~dfsg-1ubuntu3.6) ...
Selecting previously unselected package node-abab.
Preparing to unpack .../012-node-abab_2.0.5-2_all.deb ...
Unpacking node-abab (2.0.5-2) ...
Selecting previously unselected package node-ms.
Preparing to unpack .../013-node-ms_2.1.3+~cs0.7.31-2_all.deb ...
Unpacking node-ms (2.1.3+~cs0.7.31-2) ...
Selecting previously unselected package node-debug.
Preparing to unpack .../014-node-debug_4.3.2+~cs4.1.7-1_all.deb ...
Unpacking node-debug (4.3.2+~cs4.1.7-1) ...
Selecting previously unselected package node-yallist.
Preparing to unpack .../015-node-yallist_4.0.0+~4.0.1-1_all.deb ...
Unpacking node-yallist (4.0.0+~4.0.1-1) ...
Selecting previously unselected package node-lru-cache.
Preparing to unpack .../016-node-lru-cache_6.0.0+~5.1.1-1_all.deb ...
Unpacking node-lru-cache (6.0.0+~5.1.1-1) ...
Selecting previously unselected package node-semver.
Preparing to unpack .../017-node-semver_7.3.5+~7.3.8-1_all.deb ...
Unpacking node-semver (7.3.5+~7.3.8-1) ...
Selecting previously unselected package node-agent-base.
Preparing to unpack .../018-node-agent-base_6.0.2+~cs5.4.2-1_all.deb ...
Unpacking node-agent-base (6.0.2+~cs5.4.2-1) ...
Selecting previously unselected package node-ansi-regex.
Preparing to unpack .../019-node-ansi-regex_5.0.1-1_all.deb ...
Unpacking node-ansi-regex (5.0.1-1) ...
Selecting previously unselected package node-ansistyles.
Preparing to unpack .../020-node-ansistyles_0.1.3-5_all.deb ...
Unpacking node-ansistyles (0.1.3-5) ...
Selecting previously unselected package node-aproba.
Preparing to unpack .../021-node-aproba_2.0.0-2_all.deb ...
Unpacking node-aproba (2.0.0-2) ...
Selecting previously unselected package node-delegates.
Preparing to unpack .../022-node-delegates_1.0.0-3_all.deb ...
Unpacking node-delegates (1.0.0-3) ...
Selecting previously unselected package libjs-inherits.
Preparing to unpack .../023-libjs-inherits_2.0.4-4_all.deb ...
Unpacking libjs-inherits (2.0.4-4) ...
Selecting previously unselected package node-inherits.
Preparing to unpack .../024-node-inherits_2.0.4-4_all.deb ...
Unpacking node-inherits (2.0.4-4) ...
Selecting previously unselected package node-core-util-is.
Preparing to unpack .../025-node-core-util-is_1.0.3-1_all.deb ...
Unpacking node-core-util-is (1.0.3-1) ...
Selecting previously unselected package node-safe-buffer.
Preparing to unpack .../026-node-safe-buffer_5.2.1+~cs2.1.2-2_all.deb ...
Unpacking node-safe-buffer (5.2.1+~cs2.1.2-2) ...
Selecting previously unselected package node-string-decoder.
Preparing to unpack .../027-node-string-decoder_1.3.0-5_all.deb ...
Unpacking node-string-decoder (1.3.0-5) ...
Selecting previously unselected package node-process-nextick-args.
Preparing to unpack .../028-node-process-nextick-args_2.0.1-2_all.deb ...
Unpacking node-process-nextick-args (2.0.1-2) ...
Selecting previously unselected package node-util-deprecate.
Preparing to unpack .../029-node-util-deprecate_1.0.2-3_all.deb ...
Unpacking node-util-deprecate (1.0.2-3) ...
Selecting previously unselected package node-isarray.
Preparing to unpack .../030-node-isarray_2.0.5-3_all.deb ...
Unpacking node-isarray (2.0.5-3) ...
Selecting previously unselected package node-readable-stream.
Preparing to unpack .../031-node-readable-stream_3.6.0+~cs3.0.0-1_all.deb ...
Unpacking node-readable-stream (3.6.0+~cs3.0.0-1) ...
Selecting previously unselected package node-are-we-there-yet.
Preparing to unpack .../032-node-are-we-there-yet_3.0.0+~1.1.0-1_all.deb ...
Unpacking node-are-we-there-yet (3.0.0+~1.1.0-1) ...
Selecting previously unselected package node-arrify.
Preparing to unpack .../033-node-arrify_2.0.1-2_all.deb ...
Unpacking node-arrify (2.0.1-2) ...
Selecting previously unselected package node-asap.
Preparing to unpack .../034-node-asap_2.0.6+~2.0.0-1_all.deb ...
Unpacking node-asap (2.0.6+~2.0.0-1) ...
Selecting previously unselected package node-asynckit.
Preparing to unpack .../035-node-asynckit_0.4.0-4_all.deb ...
Unpacking node-asynckit (0.4.0-4) ...
Selecting previously unselected package node-builtins.
Preparing to unpack .../036-node-builtins_4.0.0-1_all.deb ...
Unpacking node-builtins (4.0.0-1) ...
Selecting previously unselected package node-chownr.
Preparing to unpack .../037-node-chownr_2.0.0-1_all.deb ...
Unpacking node-chownr (2.0.0-1) ...
Selecting previously unselected package node-fs.realpath.
Preparing to unpack .../038-node-fs.realpath_1.0.0-2_all.deb ...
Unpacking node-fs.realpath (1.0.0-2) ...
Selecting previously unselected package node-wrappy.
Preparing to unpack .../039-node-wrappy_1.0.2-2_all.deb ...
Unpacking node-wrappy (1.0.2-2) ...
Selecting previously unselected package node-once.
Preparing to unpack .../040-node-once_1.4.0-4_all.deb ...
Unpacking node-once (1.4.0-4) ...
Selecting previously unselected package node-inflight.
Preparing to unpack .../041-node-inflight_1.0.6-2_all.deb ...
Unpacking node-inflight (1.0.6-2) ...
Selecting previously unselected package node-balanced-match.
Preparing to unpack .../042-node-balanced-match_2.0.0-1_all.deb ...
Unpacking node-balanced-match (2.0.0-1) ...
Selecting previously unselected package node-brace-expansion.
Preparing to unpack .../043-node-brace-expansion_2.0.1-1_all.deb ...
Unpacking node-brace-expansion (2.0.1-1) ...
Selecting previously unselected package node-minimatch.
Preparing to unpack .../044-node-minimatch_3.1.1+~3.0.5-1_all.deb ...
Unpacking node-minimatch (3.1.1+~3.0.5-1) ...
Selecting previously unselected package node-path-is-absolute.
Preparing to unpack .../045-node-path-is-absolute_2.0.0-2_all.deb ...
Unpacking node-path-is-absolute (2.0.0-2) ...
Selecting previously unselected package node-glob.
Preparing to unpack .../046-node-glob_7.2.1+~cs7.6.15-1_all.deb ...
Unpacking node-glob (7.2.1+~cs7.6.15-1) ...
Selecting previously unselected package node-graceful-fs.
Preparing to unpack .../047-node-graceful-fs_4.2.4+repack-1_all.deb ...
Unpacking node-graceful-fs (4.2.4+repack-1) ...
Selecting previously unselected package node-mkdirp.
Preparing to unpack .../048-node-mkdirp_1.0.4+~1.0.2-1_all.deb ...
Unpacking node-mkdirp (1.0.4+~1.0.2-1) ...
Selecting previously unselected package node-iferr.
Preparing to unpack .../049-node-iferr_1.0.2+~1.0.2-1_all.deb ...
Unpacking node-iferr (1.0.2+~1.0.2-1) ...
Selecting previously unselected package node-imurmurhash.
Preparing to unpack .../050-node-imurmurhash_0.1.4+dfsg+~0.1.1-1_all.deb ...
Unpacking node-imurmurhash (0.1.4+dfsg+~0.1.1-1) ...
Selecting previously unselected package node-fs-write-stream-atomic.
Preparing to unpack .../051-node-fs-write-stream-atomic_1.0.10-5_all.deb ...
Unpacking node-fs-write-stream-atomic (1.0.10-5) ...
Selecting previously unselected package node-rimraf.
Preparing to unpack .../052-node-rimraf_3.0.2-1_all.deb ...
Unpacking node-rimraf (3.0.2-1) ...
Selecting previously unselected package node-run-queue.
Preparing to unpack .../053-node-run-queue_2.0.0-2_all.deb ...
Unpacking node-run-queue (2.0.0-2) ...
Selecting previously unselected package node-copy-concurrently.
Preparing to unpack .../054-node-copy-concurrently_1.0.5-8_all.deb ...
Unpacking node-copy-concurrently (1.0.5-8) ...
Selecting previously unselected package node-move-concurrently.
Preparing to unpack .../055-node-move-concurrently_1.0.1-4_all.deb ...
Unpacking node-move-concurrently (1.0.1-4) ...
Selecting previously unselected package node-escape-string-regexp.
Preparing to unpack .../056-node-escape-string-regexp_4.0.0-2_all.deb ...
Unpacking node-escape-string-regexp (4.0.0-2) ...
Selecting previously unselected package node-indent-string.
Preparing to unpack .../057-node-indent-string_4.0.0-2_all.deb ...
Unpacking node-indent-string (4.0.0-2) ...
Selecting previously unselected package node-p-map.
Preparing to unpack .../058-node-p-map_4.0.0+~3.1.0+~3.0.1-1_all.deb ...
Unpacking node-p-map (4.0.0+~3.1.0+~3.0.1-1) ...
Selecting previously unselected package node-promise-inflight.
Preparing to unpack .../059-node-promise-inflight_1.0.1+~1.0.0-1_all.deb ...
Unpacking node-promise-inflight (1.0.1+~1.0.0-1) ...
Selecting previously unselected package node-ssri.
Preparing to unpack .../060-node-ssri_8.0.1-2_all.deb ...
Unpacking node-ssri (8.0.1-2) ...
Selecting previously unselected package node-unique-filename.
Preparing to unpack .../061-node-unique-filename_1.1.1+ds-1_all.deb ...
Unpacking node-unique-filename (1.1.1+ds-1) ...
Selecting previously unselected package node-cacache.
Preparing to unpack .../062-node-cacache_15.0.5+~cs13.9.21-3_all.deb ...
Unpacking node-cacache (15.0.5+~cs13.9.21-3) ...
Selecting previously unselected package node-clean-yaml-object.
Preparing to unpack .../063-node-clean-yaml-object_0.1.0-5_all.deb ...
Unpacking node-clean-yaml-object (0.1.0-5) ...
Selecting previously unselected package node-clone.
Preparing to unpack .../064-node-clone_2.1.2-3_all.deb ...
Unpacking node-clone (2.1.2-3) ...
Selecting previously unselected package node-color-name.
Preparing to unpack .../065-node-color-name_1.1.4+~1.1.1-2_all.deb ...
Unpacking node-color-name (1.1.4+~1.1.1-2) ...
Selecting previously unselected package node-color-convert.
Preparing to unpack .../066-node-color-convert_2.0.1-1_all.deb ...
Unpacking node-color-convert (2.0.1-1) ...
Selecting previously unselected package node-colors.
Preparing to unpack .../067-node-colors_1.4.0-3_all.deb ...
Unpacking node-colors (1.4.0-3) ...
Selecting previously unselected package node-strip-ansi.
Preparing to unpack .../068-node-strip-ansi_6.0.1-1_all.deb ...
Unpacking node-strip-ansi (6.0.1-1) ...
Selecting previously unselected package node-defaults.
Preparing to unpack .../069-node-defaults_1.0.3+~1.0.3-1_all.deb ...
Unpacking node-defaults (1.0.3+~1.0.3-1) ...
Selecting previously unselected package node-wcwidth.js.
Preparing to unpack .../070-node-wcwidth.js_1.0.2-1_all.deb ...
Unpacking node-wcwidth.js (1.0.2-1) ...
Selecting previously unselected package node-columnify.
Preparing to unpack .../071-node-columnify_1.5.4+~1.5.1-1_all.deb ...
Unpacking node-columnify (1.5.4+~1.5.1-1) ...
Selecting previously unselected package node-console-control-strings.
Preparing to unpack .../072-node-console-control-strings_1.1.0-2_all.deb ...
Unpacking node-console-control-strings (1.1.0-2) ...
Selecting previously unselected package node-growl.
Preparing to unpack .../073-node-growl_1.10.5-4_all.deb ...
Unpacking node-growl (1.10.5-4) ...
Selecting previously unselected package node-sprintf-js.
Preparing to unpack .../074-node-sprintf-js_1.1.2+ds1+~1.1.2-1_all.deb ...
Unpacking node-sprintf-js (1.1.2+ds1+~1.1.2-1) ...
Selecting previously unselected package node-argparse.
Preparing to unpack .../075-node-argparse_2.0.1-2_all.deb ...
Unpacking node-argparse (2.0.1-2) ...
Selecting previously unselected package node-esprima.
Preparing to unpack .../076-node-esprima_4.0.1+ds+~4.0.3-2_all.deb ...
Unpacking node-esprima (4.0.1+ds+~4.0.3-2) ...
Selecting previously unselected package node-js-yaml.
Preparing to unpack .../077-node-js-yaml_4.1.0+dfsg+~4.0.5-6_all.deb ...
Unpacking node-js-yaml (4.1.0+dfsg+~4.0.5-6) ...
Selecting previously unselected package node-lcov-parse.
Preparing to unpack .../078-node-lcov-parse_1.0.0+20170612git80d039574ed9-5_all.deb ...
Unpacking node-lcov-parse (1.0.0+20170612git80d039574ed9-5) ...
Selecting previously unselected package node-log-driver.
Preparing to unpack .../079-node-log-driver_1.2.7+git+20180219+bba1761737-7_all.deb ...
Unpacking node-log-driver (1.2.7+git+20180219+bba1761737-7) ...
Selecting previously unselected package node-is-plain-obj.
Preparing to unpack .../080-node-is-plain-obj_3.0.0-2_all.deb ...
Unpacking node-is-plain-obj (3.0.0-2) ...
Selecting previously unselected package node-is-buffer.
Preparing to unpack .../081-node-is-buffer_2.0.5-2_all.deb ...
Unpacking node-is-buffer (2.0.5-2) ...
Selecting previously unselected package node-kind-of.
Preparing to unpack .../082-node-kind-of_6.0.3+dfsg-2_all.deb ...
Unpacking node-kind-of (6.0.3+dfsg-2) ...
Selecting previously unselected package node-minimist.
Preparing to unpack .../083-node-minimist_1.2.5+~cs5.3.2-1_all.deb ...
Unpacking node-minimist (1.2.5+~cs5.3.2-1) ...
Selecting previously unselected package node-cssom.
Preparing to unpack .../084-node-cssom_0.4.4-3_all.deb ...
Unpacking node-cssom (0.4.4-3) ...
Selecting previously unselected package node-cssstyle.
Preparing to unpack .../085-node-cssstyle_2.3.0-2_all.deb ...
Unpacking node-cssstyle (2.3.0-2) ...
Selecting previously unselected package node-delayed-stream.
Preparing to unpack .../086-node-delayed-stream_1.0.0-5_all.deb ...
Unpacking node-delayed-stream (1.0.0-5) ...
Selecting previously unselected package node-combined-stream.
Preparing to unpack .../087-node-combined-stream_1.0.8+~1.0.3-1_all.deb ...
Unpacking node-combined-stream (1.0.8+~1.0.3-1) ...
Selecting previously unselected package node-mime.
Preparing to unpack .../088-node-mime_3.0.0+dfsg+~cs3.96.1-1_all.deb ...
Unpacking node-mime (3.0.0+dfsg+~cs3.96.1-1) ...
Selecting previously unselected package node-mime-types.
Preparing to unpack .../089-node-mime-types_2.1.33-1_all.deb ...
Unpacking node-mime-types (2.1.33-1) ...
Selecting previously unselected package node-form-data.
Preparing to unpack .../090-node-form-data_3.0.1-1_all.deb ...
Unpacking node-form-data (3.0.1-1) ...
Selecting previously unselected package node-events.
Preparing to unpack .../091-node-events_3.3.0+~3.0.0-2_all.deb ...
Unpacking node-events (3.3.0+~3.0.0-2) ...
Selecting previously unselected package node-https-proxy-agent.
Preparing to unpack .../092-node-https-proxy-agent_5.0.0+~cs8.0.0-3_all.deb ...
Unpacking node-https-proxy-agent (5.0.0+~cs8.0.0-3) ...
Selecting previously unselected package node-iconv-lite.
Preparing to unpack .../093-node-iconv-lite_0.6.3-2_all.deb ...
Unpacking node-iconv-lite (0.6.3-2) ...
Selecting previously unselected package node-lodash-packages.
Preparing to unpack .../094-node-lodash-packages_4.17.21+dfsg+~cs8.31.198.20210220-5_all.deb ...
Unpacking node-lodash-packages (4.17.21+dfsg+~cs8.31.198.20210220-5) ...
Selecting previously unselected package node-stealthy-require.
Preparing to unpack .../095-node-stealthy-require_1.1.1-5_all.deb ...
Unpacking node-stealthy-require (1.1.1-5) ...
Selecting previously unselected package node-punycode.
Preparing to unpack .../096-node-punycode_2.1.1-5_all.deb ...
Unpacking node-punycode (2.1.1-5) ...
Selecting previously unselected package node-psl.
Preparing to unpack .../097-node-psl_1.8.0+ds-6_all.deb ...
Unpacking node-psl (1.8.0+ds-6) ...
Selecting previously unselected package node-universalify.
Preparing to unpack .../098-node-universalify_2.0.0-3_all.deb ...
Unpacking node-universalify (2.0.0-3) ...
Selecting previously unselected package node-tough-cookie.
Preparing to unpack .../099-node-tough-cookie_4.0.0-2_all.deb ...
Unpacking node-tough-cookie (4.0.0-2) ...
Selecting previously unselected package node-webidl-conversions.
Preparing to unpack .../100-node-webidl-conversions_7.0.0~1.1.0+~cs15.1.20180823-2_all.deb ...
Unpacking node-webidl-conversions (7.0.0~1.1.0+~cs15.1.20180823-2) ...
Selecting previously unselected package node-commander.
Preparing to unpack .../101-node-commander_9.0.0-2_all.deb ...
Unpacking node-commander (9.0.0-2) ...
Selecting previously unselected package node-mute-stream.
Preparing to unpack .../102-node-mute-stream_0.0.8+~0.0.1-1_all.deb ...
Unpacking node-mute-stream (0.0.8+~0.0.1-1) ...
Selecting previously unselected package node-read.
Preparing to unpack .../103-node-read_1.0.7-3_all.deb ...
Unpacking node-read (1.0.7-3) ...
Selecting previously unselected package node-ws.
Preparing to unpack .../104-node-ws_8.5.0+~cs13.3.3-2_all.deb ...
Unpacking node-ws (8.5.0+~cs13.3.3-2) ...
Selecting previously unselected package node-jsdom.
Preparing to unpack .../105-node-jsdom_19.0.0+~cs90.11.27-1_all.deb ...
Unpacking node-jsdom (19.0.0+~cs90.11.27-1) ...
Selecting previously unselected package node-fetch.
Preparing to unpack .../106-node-fetch_2.6.7+~2.5.12-1_all.deb ...
Unpacking node-fetch (2.6.7+~2.5.12-1) ...
Selecting previously unselected package node-coveralls.
Preparing to unpack .../107-node-coveralls_3.1.1-1_all.deb ...
Unpacking node-coveralls (3.1.1-1) ...
Selecting previously unselected package node-mimic-response.
Preparing to unpack .../108-node-mimic-response_3.1.0-7_all.deb ...
Unpacking node-mimic-response (3.1.0-7) ...
Selecting previously unselected package node-decompress-response.
Preparing to unpack .../109-node-decompress-response_6.0.0-2_all.deb ...
Unpacking node-decompress-response (6.0.0-2) ...
Selecting previously unselected package node-diff.
Preparing to unpack .../110-node-diff_5.0.0~dfsg+~5.0.1-3_all.deb ...
Unpacking node-diff (5.0.0~dfsg+~5.0.1-3) ...
Selecting previously unselected package node-err-code.
Preparing to unpack .../111-node-err-code_2.0.3+dfsg-3_all.deb ...
Unpacking node-err-code (2.0.3+dfsg-3) ...
Selecting previously unselected package node-time-stamp.
Preparing to unpack .../112-node-time-stamp_2.2.0-1_all.deb ...
Unpacking node-time-stamp (2.2.0-1) ...
Selecting previously unselected package node-fancy-log.
Preparing to unpack .../113-node-fancy-log_1.3.3+~cs1.3.1-2_all.deb ...
Unpacking node-fancy-log (1.3.3+~cs1.3.1-2) ...
Selecting previously unselected package node-signal-exit.
Preparing to unpack .../114-node-signal-exit_3.0.6+~3.0.1-1_all.deb ...
Unpacking node-signal-exit (3.0.6+~3.0.1-1) ...
Selecting previously unselected package node-foreground-child.
Preparing to unpack .../115-node-foreground-child_2.0.0-3_all.deb ...
Unpacking node-foreground-child (2.0.0-3) ...
Selecting previously unselected package node-function-bind.
Preparing to unpack .../116-node-function-bind_1.1.1+repacked+~1.0.3-1_all.deb ...
Unpacking node-function-bind (1.1.1+repacked+~1.0.3-1) ...
Selecting previously unselected package node-has-unicode.
Preparing to unpack .../117-node-has-unicode_2.0.1-4_all.deb ...
Unpacking node-has-unicode (2.0.1-4) ...
Selecting previously unselected package node-ansi-styles.
Preparing to unpack .../118-node-ansi-styles_4.3.0+~4.2.0-1_all.deb ...
Unpacking node-ansi-styles (4.3.0+~4.2.0-1) ...
Selecting previously unselected package node-slice-ansi.
Preparing to unpack .../119-node-slice-ansi_5.0.0+~cs9.0.0-4_all.deb ...
Unpacking node-slice-ansi (5.0.0+~cs9.0.0-4) ...
Selecting previously unselected package node-string-width.
Preparing to unpack .../120-node-string-width_4.2.3+~cs13.2.3-1_all.deb ...
Unpacking node-string-width (4.2.3+~cs13.2.3-1) ...
Selecting previously unselected package node-wide-align.
Preparing to unpack .../121-node-wide-align_1.1.3-4_all.deb ...
Unpacking node-wide-align (1.1.3-4) ...
Selecting previously unselected package node-gauge.
Preparing to unpack .../122-node-gauge_4.0.2-1_all.deb ...
Unpacking node-gauge (4.0.2-1) ...
Selecting previously unselected package node-end-of-stream.
Preparing to unpack .../123-node-end-of-stream_1.4.4+~1.4.1-1_all.deb ...
Unpacking node-end-of-stream (1.4.4+~1.4.1-1) ...
Selecting previously unselected package node-pump.
Preparing to unpack .../124-node-pump_3.0.0-5_all.deb ...
Unpacking node-pump (3.0.0-5) ...
Selecting previously unselected package node-get-stream.
Preparing to unpack .../125-node-get-stream_6.0.1-1_all.deb ...
Unpacking node-get-stream (6.0.1-1) ...
Selecting previously unselected package node-lowercase-keys.
Preparing to unpack .../126-node-lowercase-keys_2.0.0-2_all.deb ...
Unpacking node-lowercase-keys (2.0.0-2) ...
Selecting previously unselected package node-json-buffer.
Preparing to unpack .../127-node-json-buffer_3.0.1-1_all.deb ...
Unpacking node-json-buffer (3.0.1-1) ...
Selecting previously unselected package node-p-cancelable.
Preparing to unpack .../128-node-p-cancelable_2.1.1-1_all.deb ...
Unpacking node-p-cancelable (2.1.1-1) ...
Selecting previously unselected package node-quick-lru.
Preparing to unpack .../129-node-quick-lru_5.1.1-1_all.deb ...
Unpacking node-quick-lru (5.1.1-1) ...
Selecting previously unselected package node-got.
Preparing to unpack .../130-node-got_11.8.3+~cs58.7.37-1_all.deb ...
Unpacking node-got (11.8.3+~cs58.7.37-1) ...
Selecting previously unselected package node-has-flag.
Preparing to unpack .../131-node-has-flag_4.0.0-2_all.deb ...
Unpacking node-has-flag (4.0.0-2) ...
Selecting previously unselected package node-hosted-git-info.
Preparing to unpack .../132-node-hosted-git-info_4.0.2-1_all.deb ...
Unpacking node-hosted-git-info (4.0.2-1) ...
Selecting previously unselected package node-ip.
Preparing to unpack .../133-node-ip_1.1.5+~1.1.0-1_all.deb ...
Unpacking node-ip (1.1.5+~1.1.0-1) ...
Selecting previously unselected package node-ip-regex.
Preparing to unpack .../134-node-ip-regex_4.3.0+~4.1.1-1_all.deb ...
Unpacking node-ip-regex (4.3.0+~4.1.1-1) ...
Selecting previously unselected package node-is-typedarray.
Preparing to unpack .../135-node-is-typedarray_1.0.0-4_all.deb ...
Unpacking node-is-typedarray (1.0.0-4) ...
Selecting previously unselected package node-isexe.
Preparing to unpack .../136-node-isexe_2.0.0+~2.0.1-4_all.deb ...
Unpacking node-isexe (2.0.0+~2.0.1-4) ...
Selecting previously unselected package node-json-parse-better-errors.
Preparing to unpack .../137-node-json-parse-better-errors_1.0.2+~cs3.3.1-1_all.deb ...
Unpacking node-json-parse-better-errors (1.0.2+~cs3.3.1-1) ...
Selecting previously unselected package node-encoding.
Preparing to unpack .../138-node-encoding_0.1.13-2_all.deb ...
Unpacking node-encoding (0.1.13-2) ...
Selecting previously unselected package node-jsonparse.
Preparing to unpack .../139-node-jsonparse_1.3.1-10_all.deb ...
Unpacking node-jsonparse (1.3.1-10) ...
Selecting previously unselected package node-minipass.
Preparing to unpack .../140-node-minipass_3.1.6+~cs8.7.18-1_all.deb ...
Unpacking node-minipass (3.1.6+~cs8.7.18-1) ...
Selecting previously unselected package node-npm-bundled.
Preparing to unpack .../141-node-npm-bundled_1.1.2-1_all.deb ...
Unpacking node-npm-bundled (1.1.2-1) ...
Selecting previously unselected package node-osenv.
Preparing to unpack .../142-node-osenv_0.1.5+~0.1.0-1_all.deb ...
Unpacking node-osenv (0.1.5+~0.1.0-1) ...
Selecting previously unselected package node-validate-npm-package-name.
Preparing to unpack .../143-node-validate-npm-package-name_3.0.0-4_all.deb ...
Unpacking node-validate-npm-package-name (3.0.0-4) ...
Selecting previously unselected package node-npm-package-arg.
Preparing to unpack .../144-node-npm-package-arg_8.1.5-1_all.deb ...
Unpacking node-npm-package-arg (8.1.5-1) ...
Selecting previously unselected package node-object-assign.
Preparing to unpack .../145-node-object-assign_4.1.1-6_all.deb ...
Unpacking node-object-assign (4.1.1-6) ...
Selecting previously unselected package node-opener.
Preparing to unpack .../146-node-opener_1.5.2+~1.4.0-1_all.deb ...
Unpacking node-opener (1.5.2+~1.4.0-1) ...
Selecting previously unselected package node-retry.
Preparing to unpack .../147-node-retry_0.13.1+~0.12.1-1_all.deb ...
Unpacking node-retry (0.13.1+~0.12.1-1) ...
Selecting previously unselected package node-promise-retry.
Preparing to unpack .../148-node-promise-retry_2.0.1-2_all.deb ...
Unpacking node-promise-retry (2.0.1-2) ...
Selecting previously unselected package node-promzard.
Preparing to unpack .../149-node-promzard_0.3.0-2_all.deb ...
Unpacking node-promzard (0.3.0-2) ...
Selecting previously unselected package node-set-blocking.
Preparing to unpack .../150-node-set-blocking_2.0.0-2_all.deb ...
Unpacking node-set-blocking (2.0.0-2) ...
Selecting previously unselected package node-slash.
Preparing to unpack .../151-node-slash_3.0.0-2_all.deb ...
Unpacking node-slash (3.0.0-2) ...
Selecting previously unselected package libjs-source-map.
Preparing to unpack .../152-libjs-source-map_0.7.0++dfsg2+really.0.6.1-9_all.deb ...
Unpacking libjs-source-map (0.7.0++dfsg2+really.0.6.1-9) ...
Selecting previously unselected package node-source-map.
Preparing to unpack .../153-node-source-map_0.7.0++dfsg2+really.0.6.1-9_all.deb ...
Unpacking node-source-map (0.7.0++dfsg2+really.0.6.1-9) ...
Selecting previously unselected package node-source-map-support.
Preparing to unpack .../154-node-source-map-support_0.5.21+ds+~0.5.4-1_all.deb ...
Unpacking node-source-map-support (0.5.21+ds+~0.5.4-1) ...
Selecting previously unselected package node-spdx-license-ids.
Preparing to unpack .../155-node-spdx-license-ids_3.0.11-1_all.deb ...
Unpacking node-spdx-license-ids (3.0.11-1) ...
Selecting previously unselected package node-spdx-exceptions.
Preparing to unpack .../156-node-spdx-exceptions_2.3.0-2_all.deb ...
Unpacking node-spdx-exceptions (2.3.0-2) ...
Selecting previously unselected package node-spdx-expression-parse.
Preparing to unpack .../157-node-spdx-expression-parse_3.0.1+~3.0.1-1_all.deb ...
Unpacking node-spdx-expression-parse (3.0.1+~3.0.1-1) ...
Selecting previously unselected package node-spdx-correct.
Preparing to unpack .../158-node-spdx-correct_3.1.1-2_all.deb ...
Unpacking node-spdx-correct (3.1.1-2) ...
Selecting previously unselected package node-stack-utils.
Preparing to unpack .../159-node-stack-utils_2.0.5+~2.0.1-1_all.deb ...
Unpacking node-stack-utils (2.0.5+~2.0.1-1) ...
Selecting previously unselected package node-supports-color.
Preparing to unpack .../160-node-supports-color_8.1.1+~8.1.1-1_all.deb ...
Unpacking node-supports-color (8.1.1+~8.1.1-1) ...
Selecting previously unselected package node-tap-parser.
Preparing to unpack .../161-node-tap-parser_7.0.0+ds1-6_all.deb ...
Unpacking node-tap-parser (7.0.0+ds1-6) ...
Selecting previously unselected package node-tap-mocha-reporter.
Preparing to unpack .../162-node-tap-mocha-reporter_3.0.7+ds-2_all.deb ...
Unpacking node-tap-mocha-reporter (3.0.7+ds-2) ...
Selecting previously unselected package node-text-table.
Preparing to unpack .../163-node-text-table_0.2.0-4_all.deb ...
Unpacking node-text-table (0.2.0-4) ...
Selecting previously unselected package node-tmatch.
Preparing to unpack .../164-node-tmatch_5.0.0-4_all.deb ...
Unpacking node-tmatch (5.0.0-4) ...
Selecting previously unselected package node-typedarray-to-buffer.
Preparing to unpack .../165-node-typedarray-to-buffer_4.0.0-2_all.deb ...
Unpacking node-typedarray-to-buffer (4.0.0-2) ...
Selecting previously unselected package node-validate-npm-package-license.
Preparing to unpack .../166-node-validate-npm-package-license_3.0.4-2_all.deb ...
Unpacking node-validate-npm-package-license (3.0.4-2) ...
Selecting previously unselected package node-whatwg-fetch.
Preparing to unpack .../167-node-whatwg-fetch_3.6.2-5_all.deb ...
Unpacking node-whatwg-fetch (3.6.2-5) ...
Selecting previously unselected package node-write-file-atomic.
Preparing to unpack .../168-node-write-file-atomic_3.0.3+~3.0.2-1_all.deb ...
Unpacking node-write-file-atomic (3.0.3+~3.0.2-1) ...
Selecting previously unselected package nodejs-doc.
Preparing to unpack .../169-nodejs-doc_12.22.9~dfsg-1ubuntu3.6_all.deb ...
Unpacking nodejs-doc (12.22.9~dfsg-1ubuntu3.6) ...
Selecting previously unselected package node-abbrev.
Preparing to unpack .../170-node-abbrev_1.1.1+~1.1.2-1_all.deb ...
Unpacking node-abbrev (1.1.1+~1.1.2-1) ...
Selecting previously unselected package node-archy.
Preparing to unpack .../171-node-archy_1.0.0-4_all.deb ...
Unpacking node-archy (1.0.0-4) ...
Selecting previously unselected package node-chalk.
Preparing to unpack .../172-node-chalk_4.1.2-1_all.deb ...
Unpacking node-chalk (4.1.2-1) ...
Selecting previously unselected package node-cli-table.
Preparing to unpack .../173-node-cli-table_0.3.11+~cs0.13.3-1_all.deb ...
Unpacking node-cli-table (0.3.11+~cs0.13.3-1) ...
Selecting previously unselected package node-depd.
Preparing to unpack .../174-node-depd_2.0.0-2_all.deb ...
Unpacking node-depd (2.0.0-2) ...
Selecting previously unselected package node-nopt.
Preparing to unpack .../175-node-nopt_5.0.0-2_all.deb ...
Unpacking node-nopt (5.0.0-2) ...
Selecting previously unselected package node-npmlog.
Preparing to unpack .../176-node-npmlog_6.0.1+~4.1.4-1_all.deb ...
Unpacking node-npmlog (6.0.1+~4.1.4-1) ...
Selecting previously unselected package node-tar.
Preparing to unpack .../177-node-tar_6.1.11+ds1+~cs6.0.6-1_all.deb ...
Unpacking node-tar (6.1.11+ds1+~cs6.0.6-1) ...
Selecting previously unselected package node-which.
Preparing to unpack .../178-node-which_2.0.2+~cs1.3.2-2_all.deb ...
Unpacking node-which (2.0.2+~cs1.3.2-2) ...
Selecting previously unselected package node-gyp.
Preparing to unpack .../179-node-gyp_8.4.1-1_all.deb ...
Unpacking node-gyp (8.4.1-1) ...
Selecting previously unselected package node-ini.
Preparing to unpack .../180-node-ini_2.0.1-1_all.deb ...
Unpacking node-ini (2.0.1-1) ...
Selecting previously unselected package node-negotiator.
Preparing to unpack .../181-node-negotiator_0.6.2+~0.6.1-1_all.deb ...
Unpacking node-negotiator (0.6.2+~0.6.1-1) ...
Selecting previously unselected package node-resolve.
Preparing to unpack .../182-node-resolve_1.20.0+~cs5.27.9-1_all.deb ...
Unpacking node-resolve (1.20.0+~cs5.27.9-1) ...
Selecting previously unselected package node-normalize-package-data.
Preparing to unpack .../183-node-normalize-package-data_3.0.3+~2.4.1-1_all.deb ...
Unpacking node-normalize-package-data (3.0.3+~2.4.1-1) ...
Selecting previously unselected package node-read-package-json.
Preparing to unpack .../184-node-read-package-json_4.1.1-1_all.deb ...
Unpacking node-read-package-json (4.1.1-1) ...
Selecting previously unselected package node-tap.
Preparing to unpack .../185-node-tap_12.0.1+ds-4_all.deb ...
Unpacking node-tap (12.0.1+ds-4) ...
Selecting previously unselected package npm.
Preparing to unpack .../186-npm_8.5.1~ds-1_all.deb ...
Unpacking npm (8.5.1~ds-1) ...
Setting up node-delayed-stream (1.0.0-5) ...
Setting up libuv1-dev:amd64 (1.43.0-1ubuntu0.1) ...
Setting up node-fs.realpath (1.0.0-2) ...
Setting up node-diff (5.0.0~dfsg+~5.0.1-3) ...
Setting up node-abbrev (1.1.1+~1.1.2-1) ...
Setting up libjs-sprintf-js (1.1.2+ds1+~1.1.2-1) ...
Setting up node-yallist (4.0.0+~4.0.1-1) ...
Setting up libjs-inherits (2.0.4-4) ...
Setting up node-p-cancelable (2.1.1-1) ...
Setting up node-ansi-regex (5.0.1-1) ...
Setting up node-slash (3.0.0-2) ...
Setting up node-util-deprecate (1.0.2-3) ...
Setting up node-retry (0.13.1+~0.12.1-1) ...
Setting up node-arrify (2.0.1-2) ...
Setting up node-ansistyles (0.1.3-5) ...
Setting up node-delegates (1.0.0-3) ...
Setting up node-depd (2.0.0-2) ...
Setting up node-isexe (2.0.0+~2.0.1-4) ...
Setting up node-jsonparse (1.3.1-10) ...
Setting up node-escape-string-regexp (4.0.0-2) ...
Setting up libjs-source-map (0.7.0++dfsg2+really.0.6.1-9) ...
Setting up node-negotiator (0.6.2+~0.6.1-1) ...
Setting up node-color-name (1.1.4+~1.1.1-2) ...
Setting up node-growl (1.10.5-4) ...
Setting up node-indent-string (4.0.0-2) ...
Setting up libnode72:amd64 (12.22.9~dfsg-1ubuntu3.6) ...
Setting up node-function-bind (1.1.1+repacked+~1.0.3-1) ...
Setting up node-p-map (4.0.0+~3.1.0+~3.0.1-1) ...
Setting up node-iferr (1.0.2+~1.0.2-1) ...
Setting up node-chownr (2.0.0-1) ...
Setting up node-has-flag (4.0.0-2) ...
Setting up node-lodash-packages (4.17.21+dfsg+~cs8.31.198.20210220-5) ...
Setting up libjs-psl (1.8.0+ds-6) ...
Setting up node-asap (2.0.6+~2.0.0-1) ...
Setting up node-inherits (2.0.4-4) ...
Setting up node-path-is-absolute (2.0.0-2) ...
Setting up node-universalify (2.0.0-3) ...
Setting up node-ini (2.0.1-1) ...
Setting up node-safe-buffer (5.2.1+~cs2.1.2-2) ...
Setting up node-promise-inflight (1.0.1+~1.0.0-1) ...
Setting up node-json-parse-better-errors (1.0.2+~cs3.3.1-1) ...
Setting up node-sprintf-js (1.1.2+ds1+~1.1.2-1) ...
Setting up node-tmatch (5.0.0-4) ...
Setting up node-err-code (2.0.3+dfsg-3) ...
Setting up node-balanced-match (2.0.0-1) ...
Setting up node-brace-expansion (2.0.1-1) ...
Setting up node-spdx-exceptions (2.3.0-2) ...
Setting up node-set-blocking (2.0.0-2) ...
Setting up libssl-dev:amd64 (3.0.2-0ubuntu1.19) ...
Setting up node-npm-bundled (1.1.2-1) ...
Setting up node-signal-exit (3.0.6+~3.0.1-1) ...
Setting up node-source-map (0.7.0++dfsg2+really.0.6.1-9) ...
Setting up node-wrappy (1.0.2-2) ...
Setting up node-text-table (0.2.0-4) ...
Setting up node-asynckit (0.4.0-4) ...
Setting up node-ip (1.1.5+~1.1.0-1) ...
Setting up node-quick-lru (5.1.1-1) ...
Setting up node-mute-stream (0.0.8+~0.0.1-1) ...
Setting up node-mimic-response (3.1.0-7) ...
Setting up node-commander (9.0.0-2) ...
Setting up node-whatwg-fetch (3.6.2-5) ...
Setting up libjs-typedarray-to-buffer (4.0.0-2) ...
Setting up libjs-highlight.js (9.18.5+dfsg1-1) ...
Setting up node-clean-yaml-object (0.1.0-5) ...
Setting up node-ip-regex (4.3.0+~4.1.1-1) ...
Setting up node-stealthy-require (1.1.1-5) ...
Setting up node-spdx-license-ids (3.0.11-1) ...
Setting up node-string-decoder (1.3.0-5) ...
Setting up node-time-stamp (2.2.0-1) ...
Setting up libjs-events (3.3.0+~3.0.0-2) ...
Setting up node-core-util-is (1.0.3-1) ...
Setting up node-minimatch (3.1.1+~3.0.5-1) ...
Setting up node-imurmurhash (0.1.4+dfsg+~0.1.1-1) ...
Setting up node-foreground-child (2.0.0-3) ...
Setting up node-read (1.0.7-3) ...
Setting up node-is-buffer (2.0.5-2) ...
Setting up node-color-convert (2.0.1-1) ...
Setting up node-webidl-conversions (7.0.0~1.1.0+~cs15.1.20180823-2) ...
Setting up node-isarray (2.0.5-3) ...
Setting up node-osenv (0.1.5+~0.1.0-1) ...
Setting up node-is-plain-obj (3.0.0-2) ...
Setting up libjs-is-typedarray (1.0.0-4) ...
Setting up node-lowercase-keys (2.0.0-2) ...
Setting up node-decompress-response (6.0.0-2) ...
Setting up node-process-nextick-args (2.0.1-2) ...
Setting up node-has-unicode (2.0.1-4) ...
Setting up gyp (0.1+20210831gitd6c5dd5-5) ...
Setting up node-readable-stream (3.6.0+~cs3.0.0-1) ...
Setting up node-lru-cache (6.0.0+~5.1.1-1) ...
Setting up node-promise-retry (2.0.1-2) ...
Setting up node-supports-color (8.1.1+~8.1.1-1) ...
Setting up node-once (1.4.0-4) ...
Setting up libnode-dev (12.22.9~dfsg-1ubuntu3.6) ...
Setting up node-resolve (1.20.0+~cs5.27.9-1) ...
Setting up node-are-we-there-yet (3.0.0+~1.1.0-1) ...
Setting up node-kind-of (6.0.3+dfsg-2) ...
Setting up nodejs (12.22.9~dfsg-1ubuntu3.6) ...
update-alternatives: using /usr/bin/nodejs to provide /usr/bin/js (js) in auto mode
Setting up node-minimist (1.2.5+~cs5.3.2-1) ...
Setting up node-abab (2.0.5-2) ...
Setting up node-argparse (2.0.1-2) ...
Setting up node-fancy-log (1.3.3+~cs1.3.1-2) ...
Setting up node-clone (2.1.2-3) ...
Setting up node-promzard (0.3.0-2) ...
Setting up node-mime (3.0.0+dfsg+~cs3.96.1-1) ...
Setting up node-source-map-support (0.5.21+ds+~0.5.4-1) ...
Setting up node-iconv-lite (0.6.3-2) ...
Setting up node-combined-stream (1.0.8+~1.0.3-1) ...
Setting up node-unique-filename (1.1.1+ds-1) ...
Setting up node-ansi-styles (4.3.0+~4.2.0-1) ...
Setting up node-mime-types (2.1.33-1) ...
Setting up node-lcov-parse (1.0.0+20170612git80d039574ed9-5) ...
Setting up node-cssom (0.4.4-3) ...
Setting up node-form-data (3.0.1-1) ...
Setting up node-strip-ansi (6.0.1-1) ...
Setting up node-chalk (4.1.2-1) ...
Setting up node-spdx-expression-parse (3.0.1+~3.0.1-1) ...
Setting up node-which (2.0.2+~cs1.3.2-2) ...
Setting up nodejs-doc (12.22.9~dfsg-1ubuntu3.6) ...
Setting up node-punycode (2.1.1-5) ...
Setting up node-defaults (1.0.3+~1.0.3-1) ...
Setting up node-is-typedarray (1.0.0-4) ...
Setting up node-graceful-fs (4.2.4+repack-1) ...
Setting up node-inflight (1.0.6-2) ...
Setting up node-hosted-git-info (4.0.2-1) ...
Setting up node-aproba (2.0.0-2) ...
Setting up node-esprima (4.0.1+ds+~4.0.3-2) ...
Setting up node-mkdirp (1.0.4+~1.0.2-1) ...
Setting up node-run-queue (2.0.0-2) ...
Setting up node-opener (1.5.2+~1.4.0-1) ...
Setting up node-archy (1.0.0-4) ...
Setting up node-encoding (0.1.13-2) ...
Setting up node-js-yaml (4.1.0+dfsg+~4.0.5-6) ...
Setting up node-nopt (5.0.0-2) ...
Setting up node-slice-ansi (5.0.0+~cs9.0.0-4) ...
Setting up node-ms (2.1.3+~cs0.7.31-2) ...
Setting up node-semver (7.3.5+~7.3.8-1) ...
Setting up node-fs-write-stream-atomic (1.0.10-5) ...
Setting up node-builtins (4.0.0-1) ...
Setting up node-colors (1.4.0-3) ...
Setting up node-log-driver (1.2.7+git+20180219+bba1761737-7) ...
Setting up node-ssri (8.0.1-2) ...
Setting up node-object-assign (4.1.1-6) ...
Setting up node-end-of-stream (1.4.4+~1.4.1-1) ...
Setting up node-pump (3.0.0-5) ...
Setting up node-psl (1.8.0+ds-6) ...
Setting up node-stack-utils (2.0.5+~2.0.1-1) ...
Setting up node-json-buffer (3.0.1-1) ...
Setting up node-console-control-strings (1.1.0-2) ...
Setting up node-debug (4.3.2+~cs4.1.7-1) ...
Setting up node-events (3.3.0+~3.0.0-2) ...
Setting up node-agent-base (6.0.2+~cs5.4.2-1) ...
Setting up node-validate-npm-package-name (3.0.0-4) ...
Setting up node-wcwidth.js (1.0.2-1) ...
Setting up node-cssstyle (2.3.0-2) ...
Setting up node-spdx-correct (3.1.1-2) ...
Setting up node-glob (7.2.1+~cs7.6.15-1) ...
Setting up node-get-stream (6.0.1-1) ...
Setting up node-got (11.8.3+~cs58.7.37-1) ...
Setting up node-typedarray-to-buffer (4.0.0-2) ...
Setting up node-tap-parser (7.0.0+ds1-6) ...
Setting up node-minipass (3.1.6+~cs8.7.18-1) ...
Setting up node-tough-cookie (4.0.0-2) ...
Setting up node-npm-package-arg (8.1.5-1) ...
Setting up node-https-proxy-agent (5.0.0+~cs8.0.0-3) ...
Setting up node-rimraf (3.0.2-1) ...
Setting up node-string-width (4.2.3+~cs13.2.3-1) ...
Setting up node-validate-npm-package-license (3.0.4-2) ...
Setting up node-write-file-atomic (3.0.3+~3.0.2-1) ...
Setting up node-columnify (1.5.4+~1.5.1-1) ...
Setting up node-copy-concurrently (1.0.5-8) ...
Setting up node-move-concurrently (1.0.1-4) ...
Setting up node-tap-mocha-reporter (3.0.7+ds-2) ...
Setting up node-normalize-package-data (3.0.3+~2.4.1-1) ...
Setting up node-ws (8.5.0+~cs13.3.3-2) ...
Setting up node-cli-table (0.3.11+~cs0.13.3-1) ...
Setting up node-jsdom (19.0.0+~cs90.11.27-1) ...
Setting up node-tar (6.1.11+ds1+~cs6.0.6-1) ...
Setting up node-wide-align (1.1.3-4) ...
Setting up node-tap (12.0.1+ds-4) ...
Setting up node-cacache (15.0.5+~cs13.9.21-3) ...
Setting up node-read-package-json (4.1.1-1) ...
Setting up node-fetch (2.6.7+~2.5.12-1) ...
Setting up node-gauge (4.0.2-1) ...
Setting up node-npmlog (6.0.1+~4.1.4-1) ...
Setting up node-coveralls (3.1.1-1) ...
Setting up node-gyp (8.4.1-1) ...
Setting up npm (8.5.1~ds-1) ...
Processing triggers for man-db (2.10.2-1) ...
Processing triggers for libc-bin (2.35-0ubuntu3.9) ...
root@TRC:/home/trc/Videos/docker# npm cache clean --force
npm WARN using --force Recommended protections disabled.
root@TRC:/home/trc/Videos/docker# npm cache verify
Cache verified and compressed (~/.npm/_cacache)
Content verified: 0 (0 bytes)
Index entries: 0
Finished in 0.072s
root@TRC:/home/trc/Videos/docker# node server.js
internal/modules/cjs/loader.js:818
  throw err;
  ^

Error: Cannot find module 'express'
Require stack:
- /home/trc/Videos/docker/server.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:85:18)
    at Object.<anonymous> (/home/trc/Videos/docker/server.js:1:17)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/home/trc/Videos/docker/server.js' ]
}
root@TRC:/home/trc/Videos/docker# ^C
root@TRC:/home/trc/Videos/docker# node -v
v12.22.9
root@TRC:/home/trc/Videos/docker# sudo apt update && sudo apt install nodejs npm -y
Ign:1 http://dl.google.com/linux/chrome-remote-desktop/deb stable InRelease
Get:2 http://deb.anydesk.com all InRelease [7,386 B]                                                                                           
Get:3 http://security.ubuntu.com/ubuntu jammy-security InRelease [129 kB]                                                                      
Hit:4 http://archive.ubuntu.com/ubuntu jammy InRelease                                                                                         
Hit:5 https://dl.winehq.org/wine-builds/ubuntu focal InRelease                                                                                 
Ign:6 https://pkg.jenkins.io/debian binary/ InRelease                                                                                          
Hit:7 https://pkg.jenkins.io/debian binary/ Release                                                                                            
Hit:8 https://dl.google.com/linux/chrome/deb stable InRelease                                                                                  
Hit:9 http://dl.google.com/linux/chrome-remote-desktop/deb stable Release                                                                      
Get:10 http://archive.ubuntu.com/ubuntu jammy-security InRelease [129 kB]                                                                      
Err:2 http://deb.anydesk.com all InRelease                                                                                                     
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY A2FB21D5A8772835
Get:11 http://archive.ubuntu.com/ubuntu jammy-updates InRelease [128 kB]                                                                       
Get:13 http://archive.ubuntu.com/ubuntu jammy-backports InRelease [127 kB]                                                                     
Get:15 http://security.ubuntu.com/ubuntu jammy-security/universe amd64 DEP-11 Metadata [125 kB]                                                
Get:16 http://archive.ubuntu.com/ubuntu jammy-security/main amd64 DEP-11 Metadata [43.1 kB]                                                    
Get:17 http://security.ubuntu.com/ubuntu jammy-security/main amd64 DEP-11 Metadata [43.1 kB]                                                   
Hit:18 https://linux.teamviewer.com/deb stable InRelease                                                                                       
Get:19 http://security.ubuntu.com/ubuntu jammy-security/multiverse amd64 DEP-11 Metadata [208 B]                                               
Get:20 http://security.ubuntu.com/ubuntu jammy-security/restricted amd64 DEP-11 Metadata [208 B]       
Get:21 http://archive.ubuntu.com/ubuntu jammy-security/restricted amd64 DEP-11 Metadata [208 B]                         
Get:22 http://archive.ubuntu.com/ubuntu jammy-security/universe amd64 DEP-11 Metadata [125 kB]    
Get:23 http://archive.ubuntu.com/ubuntu jammy-security/multiverse amd64 DEP-11 Metadata [208 B]    
Get:24 http://archive.ubuntu.com/ubuntu jammy-updates/universe amd64 DEP-11 Metadata [359 kB]
Hit:25 https://apt.releases.hashicorp.com jammy InRelease                                        
Get:26 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 DEP-11 Metadata [103 kB]
Get:27 http://archive.ubuntu.com/ubuntu jammy-updates/multiverse amd64 DEP-11 Metadata [940 B]
Get:28 http://archive.ubuntu.com/ubuntu jammy-updates/restricted amd64 DEP-11 Metadata [212 B]
Get:29 http://archive.ubuntu.com/ubuntu jammy-backports/universe amd64 DEP-11 Metadata [17.9 kB]
Get:30 http://archive.ubuntu.com/ubuntu jammy-backports/main amd64 DEP-11 Metadata [7,020 B]
Get:31 http://archive.ubuntu.com/ubuntu jammy-backports/multiverse amd64 DEP-11 Metadata [212 B]
Get:32 http://archive.ubuntu.com/ubuntu jammy-backports/restricted amd64 DEP-11 Metadata [212 B]
Fetched 1,340 kB in 4s (300 kB/s)                       
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
52 packages can be upgraded. Run 'apt list --upgradable' to see them.
W: http://deb.anydesk.com/dists/all/InRelease: The key(s) in the keyring /etc/apt/trusted.gpg.d/anydesk.gpg are ignored as the file has an unsupported filetype.
W: An error occurred during the signature verification. The repository is not updated and the previous index files will be used. GPG error: http://deb.anydesk.com all InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY A2FB21D5A8772835
W: http://archive.ubuntu.com/ubuntu/dists/jammy/InRelease: The key(s) in the keyring /etc/apt/trusted.gpg.d/anydesk.gpg are ignored as the file has an unsupported filetype.
W: https://dl.google.com/linux/chrome/deb/dists/stable/InRelease: The key(s) in the keyring /etc/apt/trusted.gpg.d/anydesk.gpg are ignored as the file has an unsupported filetype.
W: http://dl.google.com/linux/chrome-remote-desktop/deb/dists/stable/Release.gpg: The key(s) in the keyring /etc/apt/trusted.gpg.d/anydesk.gpg are ignored as the file has an unsupported filetype.
W: http://security.ubuntu.com/ubuntu/dists/jammy-security/InRelease: The key(s) in the keyring /etc/apt/trusted.gpg.d/anydesk.gpg are ignored as the file has an unsupported filetype.
W: http://archive.ubuntu.com/ubuntu/dists/jammy-security/InRelease: The key(s) in the keyring /etc/apt/trusted.gpg.d/anydesk.gpg are ignored as the file has an unsupported filetype.
W: http://archive.ubuntu.com/ubuntu/dists/jammy-updates/InRelease: The key(s) in the keyring /etc/apt/trusted.gpg.d/anydesk.gpg are ignored as the file has an unsupported filetype.
W: http://archive.ubuntu.com/ubuntu/dists/jammy-backports/InRelease: The key(s) in the keyring /etc/apt/trusted.gpg.d/anydesk.gpg are ignored as the file has an unsupported filetype.
W: Failed to fetch http://deb.anydesk.com/dists/all/InRelease  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY A2FB21D5A8772835
W: Some index files failed to download. They have been ignored, or old ones used instead.
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
npm is already the newest version (8.5.1~ds-1).
nodejs is already the newest version (12.22.9~dfsg-1ubuntu3.6).
nodejs set to manually installed.
0 upgraded, 0 newly installed, 0 to remove and 52 not upgraded.
root@TRC:/home/trc/Videos/docker# ls
Dockerfile  package.json  server.js  styles.css
root@TRC:/home/trc/Videos/docker# node server.js
internal/modules/cjs/loader.js:818
  throw err;
  ^

Error: Cannot find module 'express'
Require stack:
- /home/trc/Videos/docker/server.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:85:18)
    at Object.<anonymous> (/home/trc/Videos/docker/server.js:1:17)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/home/trc/Videos/docker/server.js' ]
}
root@TRC:/home/trc/Videos/docker# npm install express

added 69 packages, and audited 70 packages in 7s

14 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
root@TRC:/home/trc/Videos/docker# ^C
root@TRC:/home/trc/Videos/docker# node server.js
^C
root@TRC:/home/trc/Videos/docker# docker build .
DEPRECATED: The legacy builder is deprecated and will be removed in a future release.
            Install the buildx component to build images with BuildKit:
            https://docs.docker.com/go/buildx/

Sending build context to Docker daemon  2.874MB
Step 1/6 : FROM node
latest: Pulling from library/node
155ad54a8b28: Pull complete 
8031108f3cda: Pull complete 
1d281e50d3e4: Pull complete 
447713e77b4f: Pull complete 
f8f938ab7a88: Pull complete 
174086e4b7b9: Pull complete 
074e567eb0bf: Pull complete 
32c0aebb52d8: Pull complete 
Digest: sha256:e940261391ab78a883bbcfba448bcbb6d36803053f67017e6e270ef095f213ca
Status: Downloaded newer image for node:latest
 ---> 3e5a8e2bd5a4
Step 2/6 : WORKDIR /app
 ---> Running in 1ad0c93b965f
 ---> Removed intermediate container 1ad0c93b965f
 ---> 2d6fc67eee54
Step 3/6 : COPY . /app
 ---> b968543ff00d
Step 4/6 : RUN npm install
 ---> Running in f6e8273808ad

up to date, audited 70 packages in 921ms

14 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
npm notice
npm notice New major version of npm available! 10.9.2 -> 11.2.0
npm notice Changelog: https://github.com/npm/cli/releases/tag/v11.2.0
npm notice To update run: npm install -g npm@11.2.0
npm notice
 ---> Removed intermediate container f6e8273808ad
 ---> aede56fe2fac
Step 5/6 : EXPOSE 80
 ---> Running in 037e2698ba7f
 ---> Removed intermediate container 037e2698ba7f
 ---> 75f0395cb658
Step 6/6 : CMD [ "node","server.js" ]
 ---> Running in e32036d7aec2
 ---> Removed intermediate container e32036d7aec2
 ---> 0b961a88a4e6
Successfully built 0b961a88a4e6
root@TRC:/home/trc/Videos/docker# docker images
REPOSITORY   TAG       IMAGE ID       CREATED          SIZE
<none>       <none>    0b961a88a4e6   49 seconds ago   1.13GB
node         latest    3e5a8e2bd5a4   3 days ago       1.12GB
root@TRC:/home/trc/Videos/docker# ^C
root@TRC:/home/trc/Videos/docker# docker run -p 3000:80 3e5a8e2bd5a4
root@TRC:/home/trc/Videos/docker# ^C
root@TRC:/home/trc/Videos/docker# ls
Dockerfile  node_modules  package.json  package-lock.json  server.js  styles.css
root@TRC:/home/trc/Videos/docker# npm cache clean --force
npm WARN using --force Recommended protections disabled.
root@TRC:/home/trc/Videos/docker# node server.js
curl http://localhost:3000
^C
root@TRC:/home/trc/Videos/docker# netstat -tulnp | grep 3000
root@TRC:/home/trc/Videos/docker# node server.js
^C
root@TRC:/home/trc/Videos/docker# docker images
REPOSITORY   TAG       IMAGE ID       CREATED          SIZE
<none>       <none>    0b961a88a4e6   10 minutes ago   1.13GB
node         latest    3e5a8e2bd5a4   3 days ago       1.12GB
root@TRC:/home/trc/Videos/docker# docker run -p 3000:80 0b961a88a4e6
I am completed
